# Uncomment the next line to define a global platform for your project

target 'mybookshelf' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for mybookshelf
pod 'Alamofire'
pod 'AlamofireImage'
pod 'SwiftyJSON'

end

